### ISSUE TITLE
Monthly Level Break down

### ISSUE THREAD

**Issue by dn4086** [jdharrisnz/datorama-d3-bar-pivot#1]
Hi Josh,
I am kind of new to Datorama and JS and wanted to break this viz down by Month and not by a date index. If I were to do so, which part of the code should I change?
Thanks
Dan

**Comment by jdharrisnz** [comment]
Hi Dan,

Thanks for raising this. When I first created this widget I considered adding other date options. Alas, it wasn't as popular as I'd hoped, so I never developed it further.

I'd been planning to make some updates soon, so if you like, I could include support for other date fields?

Thanks,
Josh

**Comment by dn4086** [comment]
Hey Josh,
Thanks for replying so quickly. If you can add other date formats that would be great. I loved your presentation on using custom widgets and I hope you guys can do a class in the future. Also, I was wondering whether you have a way of creating Waterfall charts as well?

**Comment by jdharrisnz** [comment]
Hi Dan,

Thanks, I appreciate it. When would you need this update?

I haven't done waterfall charts (they tend not to fit Datorama's marketing use cases), but [Highcharts has waterfall charts](https://www.highcharts.com/demo/waterfall) that you might be able to use. Joining up the custom widget data response with the format required for Highcharts is easy if you know what you're doing with JavaScript, but novices might struggle with it unfortunately.

Thanks,
Josh

**Comment by dn4086** [comment]
If you can do it in the next couple of weeks that would be awesome. But if you have other things in the pipeline, I totally understand. 
Do you think you will be adding more views to this repo?

**Comment by jdharrisnz** [comment]
Hi Dan,

This has been updated, thanks again for the feedback.

I'll add another one very soon!

Regards,
Josh
